### ISSUE TITLE
Getting error: TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by eetawil** [flatlogic/bootstrap-tabcollapse#61]
I did as the in the example provided ,please let me know what I'm missing

In my ng-controller I added:

```
 $(document).ready(function () {            
            $('#myTabs').tabCollapse(); 
}      

```

In my html I include the partial views which contains the controller info

`<div ng-include="'scripts/app/entities/asset/partials/assetCrud.html'"></div>`

I get this error in the chrome console" 

```
TypeError: Cannot read property 'childNodes' of undefined
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7518:36)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7518:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7518:13)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8108:24)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7514:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:7388:30)
    at link (http://localhost:9000/bower_components/angular/angular.js:23926:38)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8604:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8113:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7514:13) <div ng-include="'scripts/app/entities/asset/partials/assetCrud.html'" class="ng-scope">
```

**Comment by eetawil** [comment]
This fixed it:  [http://stackoverflow.com/questions/27776174/type-error-cannot-read-property-childnodes-of-undefined]

setTimeout(function(){
               jQuery('#myTab').tabCollapse(); 
            }, 0);

**Comment by vishakhag6** [comment]
I am also having this same problem with setTimeout function "dashboard.js:165 Uncaught TypeError: Cannot read property 'cancelVoucherCount' of undefined" when I am using a value less than 500. On the other hand it is working fine greater than 500. If there is any solution then let me know please.
